import { formatDateTime, formatPercent, trimText } from '../shared/masterDataUtils';

const toPercentInput = (decimal) => {
  if (decimal === null || decimal === undefined || decimal === '') return '';
  const number = Number(decimal);
  return Number.isFinite(number) ? String(number * 100) : '';
};

const toDecimal = (percentage) => {
  if (percentage === '' || percentage === null || percentage === undefined) return null;
  const number = Number(percentage);
  return Number.isFinite(number) ? number / 100 : null;
};

export const lossConfig = {
  type: 'loss',
  menuTitle: 'Loss',
  pageTitle: 'Loss Master',
  singular: 'Loss Record',
  primaryField: 'materialGroup',
  minTableWidth: 1360,
  allowEditWorkbook: true,
  excelSheetName: 'LOSS',
  importHint: 'Loss is scoped to the current Buyer. Rows with the same Material Group and all four Loss values are skipped; a repeated Material Group with different Loss values is reported as conflicting data.',

  defaultValues: {
    materialGroup: '',
    lossLt501: '',
    lossLt1501: '',
    lossLt3001: '',
    lossGte3001: ''
  },

  /*
   * Use the Material Group plus each four loss tiers as direct filters.
   * Enter normal percentage values: 3 means 3%.
   */
  searchFields: [
    {
      name: 'masterKey',
      label: 'Key',
      placeholder: 'L000001',
      sx: { flex: '0.55 1 135px' }
    },
    {
      name: 'materialGroup',
      label: 'Material Group',
      placeholder: 'Fabric, Mesh, Zipper…',
      sx: { flex: '1 1 230px' }
    },
    {
      name: 'lossLt501',
      label: 'Loss <501',
      type: 'number',
      placeholder: 'Example: 3',
      inputProps: { min: 0, max: 100, step: '0.01' },
      sx: { flex: '0.55 1 125px' }
    },
    {
      name: 'lossLt1501',
      label: 'Loss <1501',
      type: 'number',
      placeholder: 'Example: 2.5',
      inputProps: { min: 0, max: 100, step: '0.01' },
      sx: { flex: '0.55 1 125px' }
    },
    {
      name: 'lossLt3001',
      label: 'Loss <3001',
      type: 'number',
      placeholder: 'Example: 2',
      inputProps: { min: 0, max: 100, step: '0.01' },
      sx: { flex: '0.55 1 125px' }
    },
    {
      name: 'lossGte3001',
      label: 'Loss ≥3001',
      type: 'number',
      placeholder: 'Example: 1.5',
      inputProps: { min: 0, max: 100, step: '0.01' },
      sx: { flex: '0.55 1 125px' }
    }
  ],

  formHint:
    'Key is auto-generated by the system, starting from L000001. Enter percentages as normal percent values: 3 means 3%. The frontend sends the decimal rate 0.03 to the backend. Loss must not increase as order quantity increases.',

  formFields: [
    {
      name: 'materialGroup',
      label: 'Material Group',
      required: true,
      maxLength: 100,
      grid: 12,
      placeholder: 'Fabric, Mesh, Zipper, Webbing…'
    },
    {
      name: 'lossLt501',
      label: 'Loss % <501',
      type: 'number',
      required: true,
      min: 0,
      max: 100,
      step: '0.01',
      grid: 6,
      helperText: 'Example: 3 = 3%'
    },
    {
      name: 'lossLt1501',
      label: 'Loss % <1501',
      type: 'number',
      required: true,
      min: 0,
      max: 100,
      step: '0.01',
      grid: 6,
      helperText: 'Example: 2.5 = 2.5%'
    },
    {
      name: 'lossLt3001',
      label: 'Loss % <3001',
      type: 'number',
      required: true,
      min: 0,
      max: 100,
      step: '0.01',
      grid: 6
    },
    {
      name: 'lossGte3001',
      label: 'Loss % ≥3001',
      type: 'number',
      required: true,
      min: 0,
      max: 100,
      step: '0.01',
      grid: 6
    }
  ],

  columns: [
    { label: 'Key', key: 'masterKey', minWidth: 110 },
    { label: 'Material Group', key: 'materialGroup', minWidth: 170 },
    {
      label: 'Loss <501',
      key: 'lossLt501',
      minWidth: 115,
      align: 'right',
      sortValue: (row) => Number(row.lossLt501 || 0),
      render: (row) => formatPercent(row.lossLt501)
    },
    {
      label: 'Factor <501',
      key: 'factorLt501',
      minWidth: 118,
      align: 'right',
      sortValue: (row) => Number(row.factorLt501 || 0),
      render: (row) => row.factorLt501 ?? '-'
    },
    {
      label: 'Loss <1501',
      key: 'lossLt1501',
      minWidth: 120,
      align: 'right',
      sortValue: (row) => Number(row.lossLt1501 || 0),
      render: (row) => formatPercent(row.lossLt1501)
    },
    {
      label: 'Factor <1501',
      key: 'factorLt1501',
      minWidth: 123,
      align: 'right',
      sortValue: (row) => Number(row.factorLt1501 || 0),
      render: (row) => row.factorLt1501 ?? '-'
    },
    {
      label: 'Loss <3001',
      key: 'lossLt3001',
      minWidth: 120,
      align: 'right',
      sortValue: (row) => Number(row.lossLt3001 || 0),
      render: (row) => formatPercent(row.lossLt3001)
    },
    {
      label: 'Factor <3001',
      key: 'factorLt3001',
      minWidth: 123,
      align: 'right',
      sortValue: (row) => Number(row.factorLt3001 || 0),
      render: (row) => row.factorLt3001 ?? '-'
    },
    {
      label: 'Loss ≥3001',
      key: 'lossGte3001',
      minWidth: 120,
      align: 'right',
      sortValue: (row) => Number(row.lossGte3001 || 0),
      render: (row) => formatPercent(row.lossGte3001)
    },
    {
      label: 'Factor ≥3001',
      key: 'factorGte3001',
      minWidth: 123,
      align: 'right',
      sortValue: (row) => Number(row.factorGte3001 || 0),
      render: (row) => row.factorGte3001 ?? '-'
    },
    {
      label: 'Updated At',
      key: 'updatedAt',
      minWidth: 145,
      hideOnSmall: true,
      isDate: true,
      render: (row) => formatDateTime(row.updatedAt)
    }
  ],

  toFormValues: (record, defaults) => ({
    ...defaults,
    ...record,
    lossLt501: toPercentInput(record?.lossLt501),
    lossLt1501: toPercentInput(record?.lossLt1501),
    lossLt3001: toPercentInput(record?.lossLt3001),
    lossGte3001: toPercentInput(record?.lossGte3001)
  }),

  validate: (values) => {
    const errors = {};
    const tiers = [
      'lossLt501',
      'lossLt1501',
      'lossLt3001',
      'lossGte3001'
    ].map((key) => Number(values[key]));

    if (tiers.every((value) => Number.isFinite(value))) {
      const [first, second, third, fourth] = tiers;

      if (first < second || second < third || third < fourth) {
        errors.lossGte3001 =
          'Loss Must Not Increase As Order Quantity Increases: <501 ≥ <1501 ≥ <3001 ≥ ≥3001.';
      }
    }

    return errors;
  },

  toPayload: (values) => ({
    materialGroup: trimText(values.materialGroup),
    lossLt501: toDecimal(values.lossLt501),
    lossLt1501: toDecimal(values.lossLt1501),
    lossLt3001: toDecimal(values.lossLt3001),
    lossGte3001: toDecimal(values.lossGte3001)
  })
};
